### ISSUE TITLE
Runnning program

### ISSUE THREAD

**Issue by CraigCaseyContreras** [aaronetz/signal-bot#3]
How exactly do you send and receive messages? Do you open a new terminal? I verified successfully and can listen. But then what? I tried sending myself text messages seeing if they appear but to no avail.

And on Signal, my phone de-registers when I register from the terminal so I can't even send notes to myself.

Thanks!

**Comment by aaronetz** [comment]
You'll need a separate number dedicated to the bot. There are free ad-supported apps that can give you a secondary number. E.g. TextNow.

**Comment by aaronetz** [comment]
As intended
