### ISSUE TITLE
Captcha request not working / need help

### ISSUE THREAD

**Issue by EscolarProgramming** [aaronetz/signal-bot#6]
**Describe the bug**
I've tried your signal bot today. If I start it with "--register-voice +XXXXXXXXXX", I get an "org.whispersystems.signalservice.api.push.exceptions.CaptchaRequiredException". So I've tried to use the provided URL to generate a captcha code, but it seems not to be possible. If I open the link on my computer, it tried to open an "signalcaptcha://"-link, which is not possible. If I open the page on my mobile phone, it tells me that the URL is invalid. What do I have to do to generate a captcha?

**To Reproduce**
1. Open the URL https://signalcaptchas.org/registration/generate.html
2. Try to generate a captcha

**Expected behavior**
A captcha should be generated

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 94.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.1
 - Browser Safari
 - Version ---

**Comment by huffiewuffie** [comment]
I'm having the same issue but I don't think the issue lies with Captcha code. The PushServiceSocket class detected a response code of 402 and throws a CaptchaRequiredException().  Based on the response body in debug the response body shows 
"Error 402 Payment Required" even though my number is already registered and there is not much information on this "Error 402 Payment Required".  Hope someone can advise on this. Cheers

**Comment by sergey-ozernyy** [comment]
Hey! I don't know if this will help you, but try it like this:
1. Open the link https://signalcaptchas.org/registration/generate.html in a browser on your computer
2. Select the correct pictures on the captcha, press "verify" (after verification the captcha it should disappear)
3. Press F12
4. Copy the token in the format "signalcaptcha://YYyyyYyyYYYYYyyYyyY"
5. Start bot with the command "--register-voice +XXXXXXXXXX --captcha signalcaptcha://YYyyyYyyYYYYYyyYyyY"

**Comment by EscolarProgramming** [comment]
Hey, I've already figured it out myself by now, but thanks for the answer anyway!
